# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger: none

pool:
  vmImage: ubuntu-latest


steps:

- script: |
    az group create --location northcentralUS --name colorapp_RG 
  displayName: 'Create ResourceGroup'

