# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger: none

stages:
- stage: deployment
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azure iac'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: "az group create \\\n  --resource-group test-rg \\\n  --location northcentralUS\n  \n"

# deploy Vnet
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azure iac'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: "az deployment group create --resource-group test-rg --template-file module/vnet.bicep"

    
  
